version: "3"

services:

  client:
    build: ./client
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - 3001:3000
    environment:
      - NODE_ENV=development
    depends_on:
      - server

  server:
    build: ./server
    restart: always
    environment:
      APP_HOST: ${HOST}
      APP_PORT: ${PORT}
      AIO_APP_PATH: ${APP_PATH}
      APP_DB_USER: ${POSTGRES_USER}
      APP_DB_PASSWORD: ${POSTGRES_PASSWORD}
      APP_DB_NAME: ${POSTGRES_DB}
      APP_COOKIE_SECRET: ${COOKIE_SECRET}
    volumes:
      - ./server:/app
    ports:
      - 9000:8000
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres
    restart: always
    volumes:
      - ./dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 15432:5432

  redis:
    image: redis
    ports:
      - 16379:6379
