version: "3"

services:
  server:
    build: ./server
    volumes:
      - ./server:/app
    ports:
      - 8000:8000
    depends_on:
      - postgres

  postgres:
      image: postgres
      volumes:
        - ./db-data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      ports:
        - 5433:5433
